# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160218_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='cpf'),
        ),
    ]
